hinesboy/mavonEditor

src/components/s-md-toolbar-left.vue
src/mavon-editor.vue

I also use the [muse-ui](https://github.com/museui/muse-ui)  UI framework to build my website.
I found that the style sheet in `src/components/s-md-toolbar-left.vue`  changed the style of the [Drawer](http://www.muse-ui.org/#/drawer) component on the page.
So I added [scoped-css-features](https://vue-loader.vuejs.org/en/features/scoped-css.html)  to avoid this problem
我也在使用 [muse-ui](https://github.com/museui/muse-ui) 这个 UI 框架构建页面 . 
我发现 `src/components/s-md-toolbar-left.vue`  中的样式表会改变页面内  [Drawer](http://www.muse-ui.org/#/drawer) 组件 `.mu-item-wrapper .mu-item` 的样式 . 
添加了 [scoped-css-features](https://vue-loader.vuejs.org/en/features/scoped-css.html) 来避免这个问题

Add "scoped" attribute to the <style> tag , prevents its style from affecting other elements on the page

---

src/mavon-editor.vue

通过设置`default_open`值，无法切换编辑和预览窗口，watch 监听存在错误。

修复动态修改default_open无效问题

---

src/components/s-md-toolbar-left.vue
src/lib/lang/pt-BR/words_pt-BR.json

Found some typos in my translation.
Also changed the image upload popup to min-width: 120px instead of width, text was overflowing in pt-BR. With this it should be as before for other languages but also fit for pt-BR

Fixed typos in pt-BR and popup size

---

src/components/md-toolbar-left.vue
src/mavon-editor.vue

该修改 仅供上传图片到服务器-》替换图片-》以及删除图片后删除content内容里面的内容

修改图片新增和删除操作

---

src/components/md-toolbar-left.vue
src/components/md-toolbar-right.vue
src/dev/app.vue
src/index.js
src/mavon-editor.vue

**Issues:**
* #300
* #239
Using `solt` add toolbar before and after.

feat(toolbar): Support custom toolbar

---

doc/cn/markdown.md
src/index.js
src/lib/mixins/markdown.js
src/mavon-editor.vue

允许自定义 markdown-it 对象：
```vue
<mavon-editor markdown-it="customMarkdownItObject" />
```

增加自定义 Markdown-It API

---

README-EN.md
README.md
src/lib/core/extra-function.js
src/mavon-editor.vue

add tabSize setting

---

README-EN.md

Changed from fullwidth forms `，` to halfwidth forms `,` .
```
Syntax Error: Unexpected character '，'
```

Fix typo in English Readme Dcocument 

---

src/lib/mixins/markdown.js

如果一個連結由#開頭的  那通常不應該在新視窗打開
例如 `<a href="#foo">foo</a>`

Don't add target="_blank" to links start with #

---

src/lib/css/mavon-editor.styl

如果使用`externalLink=false`的話，header和圖片按鈕會位移（如圖）
因為github-markdown.css剛好設定`box-sizing border-box`才正常
因此把`box-sizing border-box`加入mavonEditor的css檔案

add box-sizing border-box

---

src/lib/mixins/markdown.js

When I wrote code language that is alias for another language in markdown, I caught a 404 link for hightlight.js.
demo: https://jsfiddle.net/qf7gLw3a/745/ (see F12 developper tools)
```
load `https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/v.min.js` ← 404
```v
// wrong loading!! ("v" is an alias for "verilog")
```
----
load `https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/verilog.min.js` ← 200
```verilog
// good loading
```
```

fix hljslang target

---

package.json
src/mavon-editor.vue

https://github.com/Asjidkalam fixed the vulnerability associated with Cross-Site Scripting.
This fix is being submitted on behalf of https://github.com/Asjidkalam - they have been awarded $25 for fixing the vulnerability through the huntr bug bounty program.
Think you could fix a vulnerability like this - get involved (https://huntr.dev).
Q | A
Version Affected | ALL
Bug Fix | YES
Further References | https://github.com/418sec/mavonEditor/pull/1
Related Issue | https://github.com/hinesboy/mavonEditor/issues/472
Original Comments:
Bug fix:
Sanitized the input value on the textarea of the vNoteEdit panel using the xss module, so that it escapes all the inputs resulting in an XSS.
The XSS mitigation is implemented inside the watch: { value: function (val, oldVal) }, which passes the val …

mavonEditor - Cross-Site Scripting - Fix:

---

src/lib/toolbar_left_click.js

插入代码块时增加换行，与GitHub，Gitlab，Typora的效果保持一致。
fix #632

fix issue #632

---

src/mavon-editor.vue

当点击帮助文档区域DIV不再触发关闭窗口事件，避免点击瞄点导致页面关闭。
fix #599

fix issue #599

---

src/lib/core/extra-function.js
src/mavon-editor.vue

fix issue #649
问题产生原因：
当切换主题时，会动态加载cdn文件，后加载的样式文件会覆盖掉前面的样式，通过这种方式来达到主题的切换，而已经加载过的cdn文件是不会再加载，所以会出现往回切换不生效问题
修复方案：
通过修改路径的方式，每次只保留一个cdn样式文件

fix issue #649

---

src/lib/core/extra-function.js
src/lib/toolbar_left_click.js
src/mavon-editor.vue

fix issue #658 #632
修改后的场景为：
1. 未选中任何文本状态，点击插入代码按钮，插入如下格式，并且选中`language`：
<pre>
```language
```
</pre>
2. 选中文本状态，点击插入代码按钮，插入如下格式，并且保持选中的文本被选择：
<pre>
```
选择的文本
```
</pre>

fix issue#658,重构插入代码块逻辑

---

src/components/md-toolbar-left.vue

Fixed pop-up style issues when pages use multiple editors

---

doc/en/upload-images.md

Replace `in` with `of` 
```> x
[ [ 1, 'toto' ], [ 2, 'tata' ] ]
> for (z of x) { console.log(z)}
[ 1, 'toto' ]
[ 2, 'tata' ]
undefined
> for (z in x) { console.log(z)}
0
1```
Otherwise, trying to access img[0] does not make sense.

Update upload-images.md [replace `in` by `of` for multiple files upload]

---

README-EN.md
README.md
src/lib/core/rules.js
src/lib/mixins/markdown.js
src/mavon-editor.vue
webpack/webpack.dev.js

Feat: Enable XSS defense by default

---

doc/cn/markdown.md
doc/en/markdown.md

编辑器外渲染出来的内容和预览的内容css样式不同，是由于编辑器中导入的css样式只作用于`.markdown-body`的后代，因此写了个简单的例子说明。#69 #399 都提到了类似的问题。

添加了一个在编辑器外渲染markdown的例子

---

README-EN.md
README.md

Improve the description of the `defaultOpen` option to avoid misunderstandings

doc: Additional notes of the `defaultOpen` option 

---

src/lib/core/rules.js
src/lib/mixins/markdown.js
src/mavon-editor.vue

Fix issue #737.
The preview is not available because the src attribute is filtered out by XSS.
Markdown image syntax skips XSS processing.

fix: image cannot be previewed
